ll:
	make -C ../../.. M=$(PWD)
clean: 
	rm built-in.o   mod_partition_policy.ko  mod_partition_policy.mod.c mod_partition_policy.mod.o  mod_partition_policy.o  modules.order  Module.symvers .built-in.o.cmd .mod_partition_policy.ko.cmd  .mod_partition_policy.mod.o.cmd  .mod_partition_policy.o.cmd  
	rm -rf .tmp_versions
