ll:
	make -C ../../.. M=$(PWD)
clean: 
	rm built-in.o   mod_rsvdev.ko  mod_rsvdev.mod.c mod_rsvdev.mod.o  mod_rsvdev.o  modules.order  Module.symvers .built-in.o.cmd .mod_rsvdev.ko.cmd  .mod_rsvdev.mod.o.cmd  .mod_rsvdev.o.cmd  
	rm -rf .tmp_versions
