ll:
	make -C ../../.. M=$(PWD)
clean: 
	rm built-in.o   mod_calc.ko  mod_calc.mod.c mod_calc.mod.o  mod_calc.o  modules.order  Module.symvers .built-in.o.cmd .mod_calc.ko.cmd  .mod_calc.mod.o.cmd  .mod_calc.o.cmd  
	rm -rf .tmp_versions
