ll:
	make -C ../../.. M=$(PWD)
clean: 
	rm built-in.o   lkmhello.ko  lkmhello.mod.c lkmhello.mod.o  lkmhello.o  modules.order  Module.symvers .built-in.o.cmd .lkmhello.ko.cmd  .lkmhello.mod.o.cmd  .lkmhello.o.cmd  
	rm -rf .tmp_versions
